./issueId.sh Doctor 1111 Moritz Meister moritz@gmail.com
./issueId.sh Doctor 2222 Jioele Begini jioele@gmail.com
./issueId.sh Patient 3333 Serghei Bordea serghei@gmail.com
./issueId.sh Patient 4444 Nico Righeriu nico@gmail.com
./createParticipant.sh Doctor 5555 Jessica Parker jessika@gmail.com
./createParticipant.sh Doctor 6666 Cameron Diaz cameron@gmail.com
./createParticipant.sh Doctor 7777 Julia Roberts julia@gmail.com
./createParticipant.sh Patient 8888 Vasilii Bodarev vasilii@gmail.com
./createParticipant.sh Patient 9999 Anastasia Volochkova anastasia@gmail.com
./createParticipant.sh Patient 0000 Wladimir Klitschko wladimir@gmail.com